[2023-10-19 20:08:29 +0200] [1143001] [INFO] Starting gunicorn 21.2.0
[2023-10-19 20:08:29 +0200] [1143001] [INFO] Listening at: http://0.0.0.0:5005 (1143001)
[2023-10-19 20:08:29 +0200] [1143001] [INFO] Using worker: sync
[2023-10-19 20:08:29 +0200] [1143003] [INFO] Booting worker with pid: 1143003
[2023-10-19 20:08:29 +0200] [1143004] [INFO] Booting worker with pid: 1143004
[2023-10-19 20:08:29 +0200] [1143005] [INFO] Booting worker with pid: 1143005
[2023-10-19 20:08:29 +0200] [1143036] [INFO] Booting worker with pid: 1143036
[2023-10-19 20:08:29 +0200] [1143003] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-19 20:08:29 +0200] [1143003] [INFO] Worker exiting (pid: 1143003)
[2023-10-19 20:08:29 +0200] [1143004] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-19 20:08:29 +0200] [1143004] [INFO] Worker exiting (pid: 1143004)
[2023-10-19 20:08:29 +0200] [1143001] [ERROR] Worker (pid:1143004) exited with code 3
[2023-10-19 20:08:29 +0200] [1143001] [ERROR] Worker (pid:1143003) was sent SIGTERM!
[2023-10-19 20:08:29 +0200] [1143005] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-19 20:08:29 +0200] [1143005] [INFO] Worker exiting (pid: 1143005)
[2023-10-19 20:08:29 +0200] [1143036] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-19 20:08:29 +0200] [1143036] [INFO] Worker exiting (pid: 1143036)
[2023-10-19 20:08:29 +0200] [1143001] [ERROR] Worker (pid:1143005) exited with code 3
[2023-10-19 20:23:55 +0200] [1143282] [INFO] Starting gunicorn 21.2.0
[2023-10-19 20:23:55 +0200] [1143282] [INFO] Listening at: http://0.0.0.0:5005 (1143282)
[2023-10-19 20:23:55 +0200] [1143282] [INFO] Using worker: sync
[2023-10-19 20:23:55 +0200] [1143284] [INFO] Booting worker with pid: 1143284
[2023-10-19 20:23:55 +0200] [1143300] [INFO] Booting worker with pid: 1143300
[2023-10-19 20:23:55 +0200] [1143301] [INFO] Booting worker with pid: 1143301
[2023-10-19 20:23:55 +0200] [1143302] [INFO] Booting worker with pid: 1143302
[2023-10-19 20:23:55 +0200] [1143284] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-19 20:23:55 +0200] [1143284] [INFO] Worker exiting (pid: 1143284)
[2023-10-19 20:23:55 +0200] [1143282] [ERROR] Worker (pid:1143284) exited with code 3
[2023-10-19 20:23:55 +0200] [1143301] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-19 20:23:55 +0200] [1143301] [INFO] Worker exiting (pid: 1143301)
[2023-10-19 20:23:55 +0200] [1143300] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-19 20:23:55 +0200] [1143300] [INFO] Worker exiting (pid: 1143300)
[2023-10-19 20:23:55 +0200] [1143302] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-19 20:23:55 +0200] [1143302] [INFO] Worker exiting (pid: 1143302)
[2023-10-19 20:23:55 +0200] [1143282] [ERROR] Worker (pid:1143301) exited with code 3
[2023-10-20 07:00:55 +0200] [1159597] [INFO] Starting gunicorn 21.2.0
[2023-10-20 07:00:55 +0200] [1159597] [INFO] Listening at: http://0.0.0.0:5005 (1159597)
[2023-10-20 07:00:55 +0200] [1159597] [INFO] Using worker: sync
[2023-10-20 07:00:55 +0200] [1159602] [INFO] Booting worker with pid: 1159602
[2023-10-20 07:00:55 +0200] [1159634] [INFO] Booting worker with pid: 1159634
[2023-10-20 07:00:55 +0200] [1159635] [INFO] Booting worker with pid: 1159635
[2023-10-20 07:00:55 +0200] [1159638] [INFO] Booting worker with pid: 1159638
[2023-10-20 07:00:55 +0200] [1159602] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-20 07:00:55 +0200] [1159602] [INFO] Worker exiting (pid: 1159602)
[2023-10-20 07:00:56 +0200] [1159597] [ERROR] Worker (pid:1159602) exited with code 3
[2023-10-20 07:00:56 +0200] [1159634] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-20 07:00:56 +0200] [1159634] [INFO] Worker exiting (pid: 1159634)
[2023-10-20 07:00:56 +0200] [1159638] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-20 07:00:56 +0200] [1159638] [INFO] Worker exiting (pid: 1159638)
[2023-10-20 07:00:56 +0200] [1159635] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-20 07:00:56 +0200] [1159635] [INFO] Worker exiting (pid: 1159635)
[2023-10-20 07:00:56 +0200] [1159597] [ERROR] Worker (pid:1159634) exited with code 3
[2023-10-20 07:21:49 +0200] [1160116] [INFO] Starting gunicorn 21.2.0
[2023-10-20 07:21:49 +0200] [1160116] [INFO] Listening at: http://0.0.0.0:5005 (1160116)
[2023-10-20 07:21:49 +0200] [1160116] [INFO] Using worker: sync
[2023-10-20 07:21:49 +0200] [1160119] [INFO] Booting worker with pid: 1160119
[2023-10-20 07:21:49 +0200] [1160120] [INFO] Booting worker with pid: 1160120
[2023-10-20 07:21:49 +0200] [1160136] [INFO] Booting worker with pid: 1160136
[2023-10-20 07:21:49 +0200] [1160152] [INFO] Booting worker with pid: 1160152
[2023-10-20 07:21:49 +0200] [1160120] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-20 07:21:49 +0200] [1160120] [INFO] Worker exiting (pid: 1160120)
[2023-10-20 07:21:49 +0200] [1160119] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-20 07:21:49 +0200] [1160119] [INFO] Worker exiting (pid: 1160119)
[2023-10-20 07:21:49 +0200] [1160116] [ERROR] Worker (pid:1160120) exited with code 3
[2023-10-20 07:21:49 +0200] [1160116] [ERROR] Worker (pid:1160119) was sent SIGTERM!
[2023-10-20 07:21:49 +0200] [1160136] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-20 07:21:49 +0200] [1160136] [INFO] Worker exiting (pid: 1160136)
[2023-10-20 07:21:49 +0200] [1160152] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-20 07:21:49 +0200] [1160152] [INFO] Worker exiting (pid: 1160152)
[2023-10-20 07:21:49 +0200] [1160116] [ERROR] Worker (pid:1160136) exited with code 3
[2023-10-20 07:27:44 +0200] [1160359] [INFO] Starting gunicorn 21.2.0
[2023-10-20 07:27:44 +0200] [1160359] [INFO] Listening at: http://0.0.0.0:5005 (1160359)
[2023-10-20 07:27:44 +0200] [1160359] [INFO] Using worker: sync
[2023-10-20 07:27:44 +0200] [1160362] [INFO] Booting worker with pid: 1160362
[2023-10-20 07:27:44 +0200] [1160363] [INFO] Booting worker with pid: 1160363
[2023-10-20 07:27:44 +0200] [1160379] [INFO] Booting worker with pid: 1160379
[2023-10-20 07:27:44 +0200] [1160380] [INFO] Booting worker with pid: 1160380
[2023-10-20 07:27:45 +0200] [1160362] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-20 07:27:45 +0200] [1160362] [INFO] Worker exiting (pid: 1160362)
[2023-10-20 07:27:45 +0200] [1160359] [ERROR] Worker (pid:1160362) exited with code 3
[2023-10-20 07:27:45 +0200] [1160363] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-20 07:27:45 +0200] [1160363] [INFO] Worker exiting (pid: 1160363)
[2023-10-20 07:27:45 +0200] [1160379] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-20 07:27:45 +0200] [1160379] [INFO] Worker exiting (pid: 1160379)
[2023-10-20 07:27:45 +0200] [1160380] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-20 07:27:45 +0200] [1160380] [INFO] Worker exiting (pid: 1160380)
[2023-10-20 07:27:45 +0200] [1160359] [ERROR] Worker (pid:1160363) exited with code 3
[2023-10-20 08:27:05 +0200] [1161103] [INFO] Starting gunicorn 21.2.0
[2023-10-20 08:27:05 +0200] [1161103] [INFO] Listening at: http://0.0.0.0:5005 (1161103)
[2023-10-20 08:27:05 +0200] [1161103] [INFO] Using worker: sync
[2023-10-20 08:27:05 +0200] [1161106] [INFO] Booting worker with pid: 1161106
[2023-10-20 08:27:05 +0200] [1161107] [INFO] Booting worker with pid: 1161107
[2023-10-20 08:27:05 +0200] [1161123] [INFO] Booting worker with pid: 1161123
[2023-10-20 08:27:05 +0200] [1161124] [INFO] Booting worker with pid: 1161124
[2023-10-20 08:27:05 +0200] [1161106] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-20 08:27:05 +0200] [1161106] [INFO] Worker exiting (pid: 1161106)
[2023-10-20 08:27:05 +0200] [1161107] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-20 08:27:05 +0200] [1161107] [INFO] Worker exiting (pid: 1161107)
[2023-10-20 08:27:05 +0200] [1161103] [ERROR] Worker (pid:1161106) exited with code 3
[2023-10-20 08:27:05 +0200] [1161103] [ERROR] Worker (pid:1161107) was sent SIGTERM!
[2023-10-20 08:27:05 +0200] [1161123] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-20 08:27:05 +0200] [1161123] [INFO] Worker exiting (pid: 1161123)
[2023-10-20 08:27:05 +0200] [1161124] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/seafile/rasavenv/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.app'
[2023-10-20 08:27:05 +0200] [1161124] [INFO] Worker exiting (pid: 1161124)
[2023-10-20 08:27:05 +0200] [1161103] [ERROR] Worker (pid:1161123) exited with code 3
[2023-10-20 08:27:05 +0200] [1161103] [ERROR] Worker (pid:1161124) exited with code 3
